version: '3.7'

services:
    flask:
        command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
            - redis
    db:
        image: postgres:12-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=find_python
    redis:
        image: redis:5.0.7
        ports:
            - "6379:6379"
    celery:
        build: .
        command: celery worker -A app.celery
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/find_python
        depends_on:
            - db
            - redis
            - flask